urls:
  house_price_estimates:
    - "https://homes.co.nz/address/auckland/ponsonby/123-example-street/xxxxx"
    - "https://www.qv.co.nz/property-search/property-details/0000000/"
    - "https://www.propertyvalue.co.nz/auckland/auckland-city/ponsonby-1011/123-example-street-ponsonby-auckland-1011-00000000"
    - "https://www.realestate.co.nz/property/123-example-street-ponsonby-auckland/xxxxxxxx"
    - "https://www.oneroof.co.nz/property/auckland/ponsonby/123-example-street/xxxxx"
